import type { Metadata } from 'next';
import { Schibsted_Grotesk, Martian_Mono } from 'next/font/google';
import { ThemeProviderWrapper } from '@/providers/ThemeProviderWrapper';
import { ReduxProvider } from '@/providers/ReduxProvider';
import { Header } from '@/components/layout/navbar/header';
import '@/styles/globals.css';
import LightRays from '@/components/ui/light-rays/LightRays';

const schibstedGrotesk = Schibsted_Grotesk({
  variable: '--font-schibsted-grotesk',
  subsets: ['latin'],
});

const martianMono = Martian_Mono({
  variable: '--font-martian-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${schibstedGrotesk.variable} ${martianMono.variable} min-h-screen bg-background font-sans antialiased`}
      >
        <ThemeProviderWrapper>
          <ReduxProvider>
            <div className="absolute inset-0 top-0 z-[-1] min-h-screen">
              <LightRays
                raysOrigin="top-center"
                raysColor="#00ffff"
                raysSpeed={1.5}
                lightSpread={0.8}
                rayLength={1.2}
                followMouse={true}
                mouseInfluence={0.1}
                noiseAmount={0.1}
                distortion={0.05}
                className="custom-rays"
              />
            </div>
            <div className="relative flex min-h-screen flex-col bg-background">
              <Header />
              <main className="flex-1">{children}</main>
            </div>
          </ReduxProvider>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
